# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Gripper Controllers ---------------------------------------
finger_small_position_controller:
    type: velocity_controllers/JointPositionController
    joint: robotB/bravo/finger_small_joint
    pid:
      p: 1.0
      i: 0.0
      d: 0.0

finger_large_position_controller:
    type: velocity_controllers/JointPositionController
    joint: robotB/bravo/finger_large_joint
    pid:
      p: 1.0
      i: 0.0
      d: 0.0
  
# Joint Controller -----------------------------------------
joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - robotB/bravo/joint1
    - robotB/bravo/joint2
    - robotB/bravo/joint3
    - robotB/bravo/joint4
    - robotB/bravo/joint5
    - robotB/bravo/joint6